services:
  db:
    image: postgres:alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - appnet

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file: .env
    volumes:
      - ./frontend/dist:/usr/share/nginx/html/web
    networks:
      - appnet

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.prod
    env_file: .env
    volumes:
      - ./dashboard/dist:/usr/share/nginx/html/dashboard
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html/web
      - ./dashboard/dist:/usr/share/nginx/html/dashboard
    depends_on:
      - web
      - dashboard
      - backend
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
